version: '3.4'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-5.7}
    environment:
      MYSQL_DB: ${MYSQL_DB:-app}
      # You should definitely change the password in production
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ChangeMe}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-Example}
      volumes: db-data:/docker/db/mysql/db:rw
    ports:
      - "127.0.0.1:33063:3306"
volumes:
  db-data:
