gather_card_data:
  path: /card
  controller: App/Controller/GatherCardData::list

verification_failure:
  path: /card/verification_failure/{e}
  controller: App/Controller/GatherCardData::list
  methods: GET

verification_success:
  path: /card/verification_success
  controller: App/Controller/VerificationSuccess::list
  methods: GET